### ISSUE TITLE
sqitch doesn't install `sqitch` tool

### ISSUE THREAD

**Issue by zeha** [theory/homebrew-sqitch#13]
I have installed these formulas:
* sqitch
* sqitch_dependencies
* sqitch_pq

(All 0.9991)

But the sqitch install appears to be quite empty:

```
ls -1 /usr/local/Cellar/sqitch/0.9991
Changes
INSTALL_RECEIPT.json
LICENSE
README
README.md
```

**Comment by theory** [comment]
What happens when you run `sqitch --version`?

**Comment by zeha** [comment]
```
% sqitch --version
zsh: command not found: sqitch
```

**Comment by theory** [comment]
Hrm. I haven't built it this way in a while, but after uninstalling previous builds and updating my Brew repo, it all worked pretty well for me:

    dwhee-ma-2944 /usr/local master > brew install sqitch_pg
    ==> Installing sqitch_pg from theory/homebrew-sqitch
    ==> Installing dependencies for sqitch_pg: sqitch_dependencies, sqitch, readline, p
    ==> Installing sqitch_pg dependency: sqitch_dependencies
    ==> Downloading http://api.metacpan.org/source/DWHEELER/App-Sqitch-0.9991/META.json
    Already downloaded: /Library/Caches/Homebrew/sqitch_dependencies-0.9991.json
    ==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9991' --notest Module::Buil
    ==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9991' --notest Module::Buil
    ==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9991' --notest Class::XSAcc
    ==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9991' --notest Pod::Simple
    ==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9991' --notest Type::Tiny::
    ==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9991' --notest Clone
    ==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9991' --notest Config::GitL
    ==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9991' --notest DBI
    ==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9991' --notest DateTime
    ==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9991' --notest Devel::Stack
    ==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9991' --notest Digest::SHA
    ==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9991' --notest Encode
    ==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9991' --notest Encode::Loca
    ==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9991' --notest File::Basena
    ==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9991' --notest File::Copy
    ==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9991' --notest File::HomeDi
    ==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9991' --notest File::Path
    ==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9991' --notest File::Temp
    ==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9991' --notest Getopt::Long
    ==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9991' --notest Hash::Merge
    ==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9991' --notest IO::Pager
    ==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9991' --notest IPC::Run3
    ==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9991' --notest IPC::System:
    ==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9991' --notest List::MoreUt
    ==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9991' --notest List::Util
    ==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9991' --notest Locale::Mess
    ==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9991' --notest Locale::Text
    ==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9991' --notest Moo
    ==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9991' --notest Moo::Role
    ==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9991' --notest Moo::sificat
    ==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9991' --notest POSIX
    ==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9991' --notest Path::Class
    ==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9991' --notest PerlIO::utf8
    ==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9991' --notest Pod::Find
    ==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9991' --notest Pod::Usage
    ==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9991' --notest Scalar::Util
    ==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9991' --notest StackTrace::
    ==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9991' --notest String::Form
    ==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9991' --notest String::Shel
    ==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9991' --notest Sub::Exporte
    ==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9991' --notest Sub::Exporte
    ==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9991' --notest Sys::Hostnam
    ==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9991' --notest Template::Ti
    ==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9991' --notest Term::ANSICo
    ==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9991' --notest Throwable
    ==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9991' --notest Time::HiRes
    ==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9991' --notest Time::Local
    ==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9991' --notest Try::Tiny
    ==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9991' --notest Type::Librar
    ==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9991' --notest Type::Utils
    ==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9991' --notest Types::Stand
    ==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9991' --notest URI
    ==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9991' --notest URI::db
    ==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9991' --notest User::pwent
    ==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9991' --notest constant
    ==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9991' --notest if
    ==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9991' --notest namespace::a
    ==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9991' --notest overload
    ==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9991' --notest parent
    ==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9991' --notest strict
    ==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9991' --notest utf8
    ==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9991' --notest warnings
    🍺  /usr/local/Cellar/sqitch_dependencies/0.9991: 1414 files, 28M, built in 115 seconds
    ==> Installing sqitch_pg dependency: sqitch
    ==> Downloading http://cpan.cpantesters.org/authors/id/D/DW/DWHEELER/App-Sqitch-0.9991.tar
    ######################################################################## 100.0%
    ==> perl Build.PL --install_base '/usr/local/Cellar/sqitch/0.9991' --installed_etcdir '/us
    ==> ./Build
    ==> ./Build install
    🍺  /usr/local/Cellar/sqitch/0.9991: 235 files, 2.9M, built in 6 seconds
    ==> Installing sqitch_pg dependency: readline
    ==> Downloading https://homebrew.bintray.com/bottles/readline-6.3.8.yosemite.bottle.tar.gz
    ######################################################################## 100.0%
    ==> Pouring readline-6.3.8.yosemite.bottle.tar.gz
    ==> Caveats
    This formula is keg-only, which means it was not symlinked into /usr/local.

    Mac OS X provides similar software, and installing this software in
    parallel can cause all kinds of trouble.

    OS X provides the BSD libedit library, which shadows libreadline.
    In order to prevent conflicts when programs look for libreadline we are
    defaulting this GNU Readline installation to keg-only.

    Generally there are no consequences of this for you. If you build your
    own software and it requires this formula, you'll need to add to your
    build variables:

        LDFLAGS:  -L/usr/local/opt/readline/lib
        CPPFLAGS: -I/usr/local/opt/readline/include

    ==> Summary
    🍺  /usr/local/Cellar/readline/6.3.8: 40 files, 2.1M
    ==> Installing sqitch_pg dependency: postgresql
    ==> Downloading https://homebrew.bintray.com/bottles/postgresql-9.4.1_1.yosemite.bottle.ta
    ######################################################################## 100.0%
    ==> Pouring postgresql-9.4.1_1.yosemite.bottle.tar.gz
    ==> Caveats
    If builds of PostgreSQL 9 are failing and you have version 8.x installed,
    you may need to remove the previous version first. See:
      https://github.com/Homebrew/homebrew/issues/2510

    To migrate existing data from a previous major version (pre-9.4) of PostgreSQL, see:
      https://www.postgresql.org/docs/9.4/static/upgrading.html

    To have launchd start postgresql at login:
        ln -sfv /usr/local/opt/postgresql/*.plist ~/Library/LaunchAgents
    Then to load postgresql now:
        launchctl load ~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist
    Or, if you don't want/need launchctl, you can just run:
        postgres -D /usr/local/var/postgres
    ==> Summary
    🍺  /usr/local/Cellar/postgresql/9.4.1_1: 2996 files, 40M
    ==> Installing sqitch_pg
    ==> Downloading file:///usr/local/README.md
    ######################################################################## 100.0%
    ==> cpanm --local-lib '/usr/local/Cellar/sqitch_pg/0.9991' --notest DBD::Pg
    🍺  /usr/local/Cellar/sqitch_pg/0.9991: 11 files, 532K, built in 5 seconds
    dwhee-ma-2944 /usr/local master > sqitch --version
    sqitch (App::Sqitch) 0.9991
    dwhee-ma-2944 /usr/local master > which sqitch
    /usr/local/bin/sqitch
    dwhee-ma-2944 /usr/local master > ls -1 /usr/local/Cellar/sqitch/0.9991
    Changes
    INSTALL_RECEIPT.json
    LICENSE
    README
    README.md
    bin/
    etc/
    lib/
    man/
    dwhee-ma-2944 /usr/local master > 

So maybe uninstall everything, `brew update`, `brew doctor`, and try again?

**Comment by zeha** [comment]
Alright, I blew away my existing squitch install and some other stuff brew has accumulated over time, and now it appears to work again!

Sorry for bothering you :-)

**Comment by theory** [comment]
Glad you got it working!
