### ISSUE TITLE
Typo in project description:

### ISSUE THREAD

**Issue by eric-brechemier** [theory/homebrew-sqitch#19]
'Homebrew Forumlas for Sqitch' -> 'Homebrew Formulas for Sqitch'
on https://github.com/theory/homebrew-sqitch

**Comment by eric-brechemier** [comment]
Also, there is a typo in README.md:

'the original Sqitch Homebrew Tap forumas' -> 'the original Sqitch Homebrew Tap formulas'

**Comment by theory** [comment]
Thank you!
