### ISSUE TITLE
Error on home-brew upgrade or install

### ISSUE THREAD

**Issue by halostatue** [theory/homebrew-sqitch#22]
Have an error with sqitch 0.9995 install or upgrade:

```
==> Installing theory/sqitch/sqitch_pg
==> Downloading file:///Users/austin/.brew/README.md
Already downloaded: /Users/austin/Library/Caches/Homebrew/sqitch_pg-0.9995.md
==> cpanm --local-lib '/Users/austin/.brew/Cellar/sqitch_pg/0.9995' --notest DBD::Pg
Error: Empty installation
```

-a

**Comment by halostatue** [comment]
Hmmm. This is happening even if I go back to 0.9994 in the tap. Trying a complete uninstall. Could be a possible conflict between Sqitch, pgtap, and a cpanm-installed version of TT2. Will verify.

**Comment by halostatue** [comment]
Definitely a conflict with having pgtap installed. Now, it looks like `sqitch_pg` only installs `DBD::Pg`, so I should only need to have `sqitch`, `sqitch_dependencies`, and `pgtap` installed to make this work for everything I’m trying to do.

**Comment by theory** [comment]
Yeah, that should work.

This whole thing should probably be rewritten to install all the CPAN modules into the directory for Sqitch itself, rather than the standard Perl directories. Same for pgtap. *sigh*.

**Comment by halostatue** [comment]
The advantage to the current setup is that I could easily do `cpanm -L$(brew --prefix)/lib Template` and get tt2 working. If you make the change, it *might* be `cpanm -L$(brew --prefix sqitch)/lib Template`, but I’m not sure. Would require some testing.
