### ISSUE TITLE
Warning: Calling Utils::JSON.load is deprecated!

### ISSUE THREAD

**Issue by theory** [theory/homebrew-sqitch#27]
@marc-mabe reports:

> I'm not sure if this is the right issue tracker but on installing sqitch with Homebrew I get the following message:
> 
> ```
> Warning: Calling Utils::JSON.load is deprecated!
> Use JSON.parse instead.
> /usr/local/Homebrew/Library/Taps/theory/homebrew-sqitch/Formula/sqitch_dependencies.rb:20:in `block in install'
> Please report this to the theory/sqitch tap!
> ```
> 
> Thanks

**Comment by zachjustice** [comment]
I've had the same bug (Sierra 10.12.2)
