### ISSUE TITLE
brew install fails

### ISSUE THREAD

**Issue by robotBaby** [theory/homebrew-sqitch#33]
Error: SHA256 mismatch
Expected: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
Actual: 83f99a282d9c31205fea8aa95ca559845615c6c7f72701e110b7c5386961aba5
Archive: /Users/adatta/Library/Caches/Homebrew/sqitch_dependencies-0.9996.json
To retry an incomplete download, remove the file above

**Comment by theory** [comment]
*SIGH*. Thanks.
