### ISSUE TITLE
Install fails on OS X Yosemite

### ISSUE THREAD

**Issue by begriffs** [theory/homebrew-sqitch#9]
```
$ brew install sqitch_pg
==> Installing sqitch_pg from theory/homebrew-sqitch
==> Installing dependencies for sqitch_pg: sqitch, postgresql
==> Installing sqitch_pg dependency: sqitch
==> Downloading http://cpan.cpantesters.org/authors/id/D/DW/DWHEELER/App-Sqitch-0.999.tar.gz
Already downloaded: /Library/Caches/Homebrew/sqitch-0.999.tar.gz
==> perl Build.PL --install_base '/usr/local/Cellar/sqitch/0.999' --installed_etcdir '/usr/local/etc/sqitch'
2015-03-30 17:03:24 -0700

perl Build.PL --install_base '/usr/local/Cellar/sqitch/0.999' --installed_etcdir '/usr/local/etc/sqitch'

couldn't understand kern.osversion `14.1.0'
```

**Comment by theory** [comment]
NFI what causes that error. Oh, looks like [this might be helpful](http://stackoverflow.com/a/28742354/79202).

**Comment by begriffs** [comment]
Yeah, I hate system upgrades... I'll keep trying things and post anything I find. Just wanted to record the issue.

**Comment by chiefgecko** [comment]
sqitch_mysql builds on OSX Yosemite
sqitch_pg builds on OSX Yosemite
sqitch_sqitch_oracle fails to build on OSX Yosemite

myself@me.local [/Users/myself]
$ env | egrep "^DYLD|^PATH=|^ORACLE_[BH]"
ORACLE_BASE=/opt/oracle/base
PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/oracle/base/product/11204/instantclient_11_2
DYLD_LIBRARY_PATH=/opt/oracle/base/product/11204/instantclient_11_2
ORACLE_HOME=/opt/oracle/base/product/11204/instantclient_11_2
myself@me.local [/Users/myself]
$ which sqlplus
/opt/oracle/base/product/11204/instantclient_11_2/sqlplus
myself@me.local [/Users/myself]
$ l $ORACLE_HOME/*dylib
lrwxr-xr-x  1 root  wheel         20 Aug 31 21:08 /opt/oracle/base/product/11204/instantclient_11_2/libclntsh.dylib -> libclntsh.dylib.11.1
-r-xr-xr-x@ 1 root  wheel      13744 Jan  7  2014 /opt/oracle/base/product/11204/instantclient_11_2/libheteroxa11.dylib
-r-xr-xr-x@ 1 root  wheel    2817872 Jan 29  2014 /opt/oracle/base/product/11204/instantclient_11_2/libnnz11.dylib
lrwxr-xr-x  1 root  wheel         18 Aug 31 21:08 /opt/oracle/base/product/11204/instantclient_11_2/libocci.dylib -> libocci.dylib.11.1
-rwxrwxrwx@ 1 root  wheel  118707148 Apr 10  2014 /opt/oracle/base/product/11204/instantclient_11_2/libociei.dylib
-r-xr-xr-x@ 1 root  wheel     159004 Jan  7  2014 /opt/oracle/base/product/11204/instantclient_11_2/libocijdbc11.dylib
-r-xr-xr-x@ 1 root  wheel    1365444 Jan 27  2014 /opt/oracle/base/product/11204/instantclient_11_2/libsqlplus.dylib
-r-xr-xr-x@ 1 root  wheel    1504252 Jan  7  2014 /opt/oracle/base/product/11204/instantclient_11_2/libsqlplusic.dylib
myself@me.local [/Users/myself]
$ file $(which sqlplus)
/opt/oracle/base/product/11204/instantclient_11_2/sqlplus: Mach-O 64-bit executable x86_64
myself@me.local [/Users/myself]
$ brew info sqitch
theory/sqitch/sqitch: stable 0.9993, HEAD
http://sqitch.org/
/usr/local/Cellar/sqitch/0.9993 (243 files, 3.0M) *
  Built from source
From: https://github.com/theory/homebrew-sqitch/blob/master/Formula/sqitch.rb
==> Dependencies
Required: sqitch_dependencies ✔
myself@me.local [/Users/myself]
$ brew install sqitch_oracle
==> Installing sqitch_oracle from theory/homebrew-sqitch
==> Downloading file:///usr/local/README.md
Already downloaded: /Library/Caches/Homebrew/sqitch_oracle-0.9993.md
==> cpanm --local-lib '/usr/local/Cellar/sqitch_oracle/0.9993' --notest DBD::Oracle
--> Working on DBD::Oracle
Fetching http://www.cpan.org/authors/id/P/PY/PYTHIAN/DBD-Oracle-1.74.tar.gz ... OK
Configuring DBD-Oracle-1.74 ... OK
Building DBD-Oracle-1.74 ... ! Installing DBD::Oracle failed. See /private/tmp/sqitch_oracle20150831-34500-5cqjrl/.brew_home/.cpanm/work/1441080994.34514/build.log for details. Retry with --force to force install it.
FAIL

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/theory/homebrew-sqitch/issues

myself@me.local [/Users/myself]
$ l /private/tmp/sqitch_oracle20150831-34500-5cqjrl/.brew_home/.cpanm/work/1441080994.34514/build.log
ls: /private/tmp/sqitch_oracle20150831-34500-5cqjrl/.brew_home/.cpanm/work/1441080994.34514/build.log: No such file or directory
myself@me.local [/Users/myself]
$

**Comment by chiefgecko** [comment]
myself@me.local [/Users/myself]
$ uname -a
Darwin tim.local 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64
myself@me.local [/Users/myself]
$
